import type { SettingsSchema } from "rune-lab/core";
import { defineSettings } from "rune-lab/core";

export const layoutSettings: SettingsSchema = defineSettings({
  id: "general",
  label: "General Settings",
  icon: "settings",
  fields: [
    {
      id: "rune-lab.layout.preset",
      label: "Layout Preset",
      type: "select",
      target: {
        type: "store",
        storeId: "layout",
        property: "preset",
      },
      options: [
        { value: "page", label: "Simple Page" },
        { value: "docs", label: "Documentation" },
        { value: "workspace", label: "Workspace IDE" },
      ],
    },
    {
      id: "rune-lab.layout.theme",
      label: "Theme",
      type: "select",
      target: {
        type: "store",
        storeId: "theme",
        property: "current",
      },
      options: [
        { value: "light", label: "Light" },
        { value: "dark", label: "Dark" },
        { value: "cupcake", label: "Cupcake" },
        { value: "bumblebee", label: "Bumblebee" },
        { value: "emerald", label: "Emerald" },
        { value: "corporate", label: "Corporate" },
        { value: "synthwave", label: "Synthwave" },
        { value: "retro", label: "Retro" },
        { value: "cyberpunk", label: "Cyberpunk" },
        { value: "valentine", label: "Valentine" },
        { value: "halloween", label: "Halloween" },
        { value: "garden", label: "Garden" },
        { value: "forest", label: "Forest" },
        { value: "aqua", label: "Aqua" },
        { value: "lofi", label: "Lofi" },
        { value: "pastel", label: "Pastel" },
        { value: "fantasy", label: "Fantasy" },
        { value: "wireframe", label: "Wireframe" },
        { value: "black", label: "Black" },
        { value: "luxury", label: "Luxury" },
        { value: "dracula", label: "Dracula" },
        { value: "cmyk", label: "CMYK" },
        { value: "autumn", label: "Autumn" },
        { value: "business", label: "Business" },
        { value: "acid", label: "Acid" },
        { value: "lemonade", label: "Lemonade" },
        { value: "night", label: "Night" },
        { value: "coffee", label: "Coffee" },
        { value: "winter", label: "Winter" },
        { value: "dim", label: "Dim" },
        { value: "nord", label: "Nord" },
        { value: "sunset", label: "Sunset" },
        { value: "caramellatte", label: "Caramellatte" },
        { value: "abyss", label: "Abyss" },
        { value: "silk", label: "Silk" },
      ],
    },
  ],
});
