// Ambient declarations for paraglide-generated files.
// These are auto-generated by inlang/paraglide and hidden via .gitignore —
// they exist at runtime but are invisible to the type-checker, hence these stubs.
declare module "$lib/i18n/paraglide/runtime.js" {
  export const locales: readonly string[];
  export const baseLocale: string;
  export type Locale = (typeof locales)[number];

  export function getLocale(): Locale;
  export function setLocale(
    locale: Locale,
    options?: { reload?: boolean },
  ): void | Promise<void>;
  export function isLocale(value: unknown): value is Locale;
  export function toLocale(value: unknown): Locale | undefined;
  export function assertIsLocale(value: unknown): Locale;
  export function deLocalizeUrl(url: URL | string): URL;
  export function localizeUrl(
    url: URL | string,
    options?: { locale?: Locale },
  ): URL;
}

declare module "$lib/i18n/paraglide/server.js" {
  import type { Locale } from "$lib/i18n/paraglide/runtime.js";

  export function paraglideMiddleware<T>(
    request: Request,
    resolve: (ctx: { request: Request; locale: Locale }) => T | Promise<T>,
    callbacks?: { onRedirect: (response: Response) => void },
  ): Promise<Response>;
}
