export { corpo } from "./plugin.ts";
export { CORPO_PLUGIN_ID, getCorpoStore } from "./context.ts";
export { createCorpoStore, type CorpoStore } from "./store.svelte.ts";
export { resolveCorpoConfig } from "./config.ts";
export { createCorpoIntegration } from "./integration.ts";
export { corpoSettings } from "./settings.ts";
export type * from "./types.ts";
export { default as Logo } from "./components/Logo.svelte";
export { default as AppIdentity } from "./components/AppIdentity.svelte";
export { default as AppHeader } from "./components/AppHeader.svelte";
export { default as AppActions } from "./components/AppActions.svelte";
export { default as AppNavigation } from "./components/AppNavigation.svelte";
export { default as AppStatusbar } from "./components/AppStatusbar.svelte";
export { default as AppFooter } from "./components/AppFooter.svelte";
export { default as CorpoLayout } from "./components/CorpoLayout.svelte";
export { default as CorpoShell } from "./components/CorpoShell.svelte";
