// Locale metadata
// Locale detection & mutation
// URL localisation helpers
export {
  baseLocale,
  deLocalizeUrl,
  getLocale,
  isLocale,
  locales,
  localizeUrl,
  setLocale,
  toLocale,
} from "$lib/i18n/paraglide/runtime.js";

// SvelteKit middleware for paraglide
export { paraglideMiddleware } from "$lib/i18n/paraglide/server.js";

// Compiled message functions
// `m` contains one function per translation key (e.g. m.hello(), m.page_title()).
// The file is auto-generated by inlang/paraglide and hidden via .gitignore —
// it exists at runtime but is invisible to the type-checker, hence the ignore.
// @ts-expect-error: paraglide-js generated files are hidden by .gitignore and
// missing declarations during type-check — they exist at runtime, trust the build.
import * as m from "./paraglide/messages.js";

export { m };
